# Generated by Django 5.1.4 on 2024-12-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_region_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.district'),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.region'),
        ),
    ]
