# Generated by Django 5.1.4 on 2024-12-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_car_district_car_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
