# Generated by Django 5.1.4 on 2024-12-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
